### ISSUE TITLE
CORS issue "Access-Control-Allow-Origin"

### ISSUE THREAD

**Issue by nitesh31mishra** [agupta15k/ncsu_se_fall22_22_pr_1#27]
Facing the CORS issue while requesting the Backend route from Frontend. Getting the below error in console.  

`Access to XMLHttpRequest at 'https://f0b1-107-13-178-32.ngrok.io/additem' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Unlike Postman, the browser first sends an OPTIONS type preflight request before the actual request to check if the potential actual request is acceptable on the server or not. Since the server here is not returning the header 'Access-Control-Allow-Origin' in the response, client browser is not accepting the response, and thus not sending the actual request.

We need a way for the backend to accept the OPTIONS request and respond with an appropriate 'Access-Control-Allow-Origin' header. Since we are using localhost here, we can add that, or add '*' as the response for the time being.

Can you just check if the CORS are enabled and OPTIONS are being added in the method for the routes?

Thanks

**Comment by Arunsp2000** [comment]
Since we are using Flask Cors in the Backend. It automatically sends Access-Control-Allow-Origin' header in the response. We have now added OPTIONS in the methods for each api request to handle CORS.
