### ISSUE TITLE
Wrong exit control when XAMPP server not running

### ISSUE THREAD

**Issue by Arunsp2000** [agupta15k/ncsu_se_fall22_22_pr_1#31]
Issue with respect to test case failing in backend  when mysql server not running. Test cases using a connection variable when it does not exist.

**Comment by nitesh31mishra** [comment]
Okay. I went through the code, in the utils.py file the try-except handles the Mysql connection. In the except statement we have just written `pass` this results in not creating the connection variable in case of failure of try. And our application failes while running the functions.

I have handled this now by adding the except for Exceptions. So now this will work. Please check the push.

**Comment by Arunsp2000** [comment]
Thanks!
