### ISSUE TITLE
Add support for multiple zip codes.

### ISSUE THREAD

**Issue by nagarajumadamshetti** [agupta15k/ncsu_se_fall22_22_pr_1#5]
Able to add multiple cities, but not able to  add multiple zip codes on the registration page.

**Comment by agupta15k** [comment]
Added this functionality in [this commit](https://github.com/agupta15k/ncsu_se_fall22_22_pr_1/commit/51b0d769fc7e9cb298d5794c1c3e4d9d9382c4d1).
